"""add allocated_preference column

Revision ID: 5a812010a07a
Revises: b7d222b79da3
Create Date: 2023-03-04 14:00:10.860213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a812010a07a'
down_revision = 'b7d222b79da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_preference', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('allocated_preference')

    # ### end Alembic commands ###
